# %% [markdown]
# # 04 - Generate Label Files
#
# This notebook generates the label files required for Azure DI training:
# - `fields.json` - Schema defining all extractable fields
# - `*.labels.json` - Labels for each training image
#
# Labels are generated by matching OCR words to template zones.

# %%
# Standard imports
import os
import sys
from pathlib import Path

import cv2
import numpy as np

# Add project root to path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Load environment variables
from dotenv import load_dotenv
load_dotenv(project_root / ".env")

from src.utils import load_json, save_json, load_image
from src.alignment_wrapper import load_template_zones
from src.labels_generator import (
    generate_fields_json,
    generate_labels_json,
    generate_labels_batch,
    validate_training_data,
)
from src.ocr_generator import extract_words_from_ocr, get_page_dimensions

print(f"Project root: {project_root}")

# %% [markdown]
# ## 1. Configuration

# %%
# Paths
DATA_DIR = project_root / "data"
TRAINING_DIR = DATA_DIR / "training"
DEBUG_DIR = DATA_DIR / "debug"
TEMPLATES_DIR = project_root / "templates"

TEMPLATE_JSON_PATH = TEMPLATES_DIR / "template.json"

# Create debug directory if it doesn't exist
DEBUG_DIR.mkdir(parents=True, exist_ok=True)

print(f"Training directory: {TRAINING_DIR}")
print(f"Debug directory: {DEBUG_DIR}")
print(f"Template JSON: {TEMPLATE_JSON_PATH}")

# List training files
training_images = sorted(TRAINING_DIR.glob("*.jpg"))
ocr_files = sorted(TRAINING_DIR.glob("*.ocr.json"))

print(f"\nTraining images: {len(training_images)}")
print(f"OCR JSON files: {len(ocr_files)}")

# %% [markdown]
# ## 2. Load Template Zones

# %%
# Load template zones
zones = load_template_zones(TEMPLATE_JSON_PATH)

print("Template Zones Loaded:")
print("-" * 50)
print(f"Polygon zones: {len(zones['polygon_zones'])}")
print(f"Rectangle zones: {len(zones['rectangle_zones'])}")
print(f"Checkbox zones: {len(zones['checkbox_zones'])}")
print(f"Image dimensions: {zones['image_width']} x {zones['image_height']}")

# %%
# List field categories
print("\nField Categories:")
print("-" * 50)

categories = zones['categories']
for cat_id, name in sorted(categories.items())[:20]:
    print(f"  {cat_id:3d}: {name}")

if len(categories) > 20:
    print(f"  ... and {len(categories) - 20} more")

print(f"\nTotal categories: {len(categories)}")

# %% [markdown]
# ## 3. Generate fields.json

# %%
# Generate fields.json
fields_output_path = TRAINING_DIR / "fields.json"

fields_data = generate_fields_json(
    categories=zones['categories'],
    output_path=fields_output_path,
    exclude_checkboxes=False,  # Include checkbox fields
)

print(f"Generated fields.json with {len(fields_data['fields'])} fields")
print(f"Saved to: {fields_output_path}")

# %%
# Show field definitions
print("\nField Definitions (sample):")
print("-" * 60)
print(f"{'Name':<40} {'Type':<15} {'Subtype'}")
print("-" * 60)

for field in fields_data['fields'][:15]:
    subtype = field.get('subtype', '')
    print(f"{field['name']:<40} {field['type']:<15} {subtype}")

if len(fields_data['fields']) > 15:
    print(f"... and {len(fields_data['fields']) - 15} more fields")

# %% [markdown]
# ## 4. Generate Labels for Single Image (Demo)

# %%
# Demo with first image
if training_images and ocr_files:
    demo_image = training_images[0]
    demo_ocr_path = TRAINING_DIR / f"{demo_image.name}.ocr.json"

    if demo_ocr_path.exists():
        demo_ocr_data = load_json(demo_ocr_path)

        demo_labels_path = TRAINING_DIR / f"{demo_image.name}.labels.json"

        labels_data = generate_labels_json(
            image_name=demo_image.name,
            ocr_data=demo_ocr_data,
            zones=zones,
            output_path=demo_labels_path,
        )

        print(f"Generated labels for: {demo_image.name}")
        print(f"Labels count: {len(labels_data['labels'])}")
        print(f"Saved to: {demo_labels_path}")

# %%
# Show sample labels
if 'labels_data' in dir():
    print("\nSample Labels:")
    print("-" * 70)

    for label in labels_data['labels'][:10]:
        name = label['label']
        label_type = label['labelType']
        values = label.get('value', [])

        if values:
            text = values[0].get('text', '')[:40]
            bbox_count = len(values[0].get('boundingBoxes', []))
        else:
            text = ''
            bbox_count = 0

        print(f"  {name:<35} [{label_type:<14}] '{text}' ({bbox_count} boxes)")

    if len(labels_data['labels']) > 10:
        print(f"  ... and {len(labels_data['labels']) - 10} more labels")

# %% [markdown]
# ## 5. Save Debug Images with Labels

# %%
def save_debug_image(image_path, labels_data, output_dir):
    """
    Save debug image showing labeled regions with field names.

    Args:
        image_path: Path to the training image
        labels_data: Labels data dictionary
        output_dir: Directory to save debug images
    """
    # Load image
    image = load_image(image_path)
    height, width = image.shape[:2]

    # Create a copy for drawing
    debug_image = image.copy()

    # Generate colors for different fields
    np.random.seed(42)  # Consistent colors
    colors = [(np.random.randint(50, 255),
               np.random.randint(50, 255),
               np.random.randint(50, 255))
              for _ in range(len(labels_data['labels']))]

    # Draw labeled regions
    for i, label in enumerate(labels_data['labels']):
        color = colors[i % len(colors)]
        name = label['label']

        for value in label.get('value', []):
            text_content = value.get('text', '')

            for bbox in value.get('boundingBoxes', []):
                # Convert normalized coords back to pixels
                # bbox format: [x1,y1, x2,y1, x2,y2, x1,y2]
                x1 = int(bbox[0] * width)
                y1 = int(bbox[1] * height)
                x2 = int(bbox[2] * width)
                y2 = int(bbox[5] * height)

                # Draw rectangle
                cv2.rectangle(debug_image, (x1, y1), (x2, y2), color, 2)

                # Add field name above the box
                label_text = f"{name}: {text_content}"
                font = cv2.FONT_HERSHEY_SIMPLEX
                font_scale = 0.5
                thickness = 1

                # Get text size for background
                (text_width, text_height), baseline = cv2.getTextSize(
                    label_text, font, font_scale, thickness
                )

                # Draw background for text
                text_y = max(y1 - 5, text_height + 5)
                cv2.rectangle(
                    debug_image,
                    (x1, text_y - text_height - baseline),
                    (x1 + text_width, text_y + baseline),
                    color,
                    -1  # Filled
                )

                # Draw text
                cv2.putText(
                    debug_image,
                    label_text,
                    (x1, text_y),
                    font,
                    font_scale,
                    (255, 255, 255),  # White text
                    thickness,
                    cv2.LINE_AA
                )

    # Save debug image
    output_path = output_dir / f"{image_path.stem}_debug.jpg"
    cv2.imwrite(str(output_path), debug_image)

    return output_path

# Generate debug image for demo
if 'labels_data' in dir() and training_images:
    debug_path = save_debug_image(training_images[0], labels_data, DEBUG_DIR)
    print(f"\nSaved debug image: {debug_path}")

# %% [markdown]
# ## 6. Batch Generate Labels for All Images

# %%
# Prepare image-OCR pairs
image_ocr_pairs = []

for img_path in training_images:
    ocr_path = TRAINING_DIR / f"{img_path.name}.ocr.json"

    # Skip if labels already exist
    labels_path = TRAINING_DIR / f"{img_path.name}.labels.json"
    if labels_path.exists():
        continue

    if ocr_path.exists():
        ocr_data = load_json(ocr_path)
        image_ocr_pairs.append((img_path.name, ocr_data))

print(f"Images to process: {len(image_ocr_pairs)}")
print(f"Already processed: {len(training_images) - len(image_ocr_pairs)}")

# %%
# Generate labels for remaining images
if image_ocr_pairs:
    print(f"\nGenerating labels for {len(image_ocr_pairs)} images...")

    results = generate_labels_batch(
        image_ocr_pairs=image_ocr_pairs,
        zones=zones,
        output_dir=TRAINING_DIR,
        verbose=True,
    )

    # Summary
    successful = sum(1 for r in results if r.get('success'))
    print(f"\nGenerated labels for {successful}/{len(results)} images")

    # Show any failures
    failures = [r for r in results if not r.get('success')]
    if failures:
        print("\nFailed:")
        for f in failures:
            print(f"  - {f['image']}: {f.get('error', 'Unknown')}")
else:
    print("All images already have labels.")

# %% [markdown]
# ## 6.5. Generate Debug Images for All Processed Images

# %%
# Generate debug images for all images with labels
print("\nGenerating debug images for all processed images...")

debug_count = 0
for img_path in training_images:
    labels_path = TRAINING_DIR / f"{img_path.name}.labels.json"

    if labels_path.exists():
        try:
            labels_data = load_json(labels_path)
            debug_path = save_debug_image(img_path, labels_data, DEBUG_DIR)
            debug_count += 1
            print(f"  Generated: {debug_path.name}")
        except Exception as e:
            print(f"  Failed for {img_path.name}: {e}")

print(f"\nGenerated {debug_count} debug images in {DEBUG_DIR}")

# %% [markdown]
# ## 7. Validate Training Data

# %%
# Validate the complete training dataset
validation = validate_training_data(TRAINING_DIR)

print("\nTraining Data Validation:")
print("=" * 60)
print(f"Status: {'VALID' if validation['valid'] else 'INVALID'}")
print(f"Image count: {validation['image_count']}")
print(f"Directory: {validation['training_dir']}")

if validation['issues']:
    print("\nIssues:")
    for issue in validation['issues']:
        print(f"  - {issue}")
else:
    print("\nNo issues found.")

# %% [markdown]
# ## 8. Training Data Summary

# %%
# List all training files
print("\nTraining Data Contents:")
print("-" * 60)

# Count files by type
images = list(TRAINING_DIR.glob("*.jpg"))
ocr_files = list(TRAINING_DIR.glob("*.ocr.json"))
labels_files = list(TRAINING_DIR.glob("*.labels.json"))
fields_json = TRAINING_DIR / "fields.json"

print(f"Images: {len(images)}")
print(f"OCR JSON files: {len(ocr_files)}")
print(f"Labels JSON files: {len(labels_files)}")
print(f"fields.json: {'YES' if fields_json.exists() else 'NO'}")

# Show completeness per image
print("\nPer-image completeness:")
for img in sorted(images):
    ocr_ok = (TRAINING_DIR / f"{img.name}.ocr.json").exists()
    labels_ok = (TRAINING_DIR / f"{img.name}.labels.json").exists()
    status = "COMPLETE" if ocr_ok and labels_ok else "INCOMPLETE"
    print(f"  {img.name}: {status}")

# %%
print("\n" + "=" * 60)
print("LABELS GENERATION SUMMARY")
print("=" * 60)

if validation['valid']:
    print("\nTraining data is complete and valid!")
    print(f"Total samples: {validation['image_count']}")
    print("\nYou can proceed to the next notebook: 05_upload_to_blob.py")
else:
    print("\nTraining data has issues that need to be resolved.")
    print("Please check the validation issues above.")

# %%
